name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.sonar/cache
            ./.sonar/scanner
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          # Verifica se o diretório do scanner já existe e remove se necessário
          if (Test-Path .\.sonar\scanner) {
            Remove-Item -Recurse -Force .\.sonar\scanner
          }
          New-Item -Path .\.sonar\scanner -ItemType Directory -Force
          
          # Instala o SonarQube scanner
          dotnet tool install dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Build and analyze
        shell: powershell
        run: |
          # Inicia a análise do SonarQube
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Eficaz-WebApi" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarqube.labs.unimar.br"
          
          # Realiza o build do projeto
          dotnet build
          
          # Finaliza a análise do SonarQube
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
